
clear

config_comparative
%config_effective

repetitions = 1;


%% Run optimization
res = runOptBatch(platPath, ...
    sNSGAIIPath, ...
    repetitions, ...
    algorithms, ...
    sps_on, ... 
    labels, ...
    max_ref, ...
    prob, ...
    indep_var_dec_vars, ...
    defaultDecVar, ...
    defaultSparsity, ...
    Dz, ...
    sparsities);


