
clear;
cropoverTest_comp;

output_files = { ...
    'Z:\Gilgamesh\kroppian\sNSGAIIRuns\island\sNSGAIIComparative_compDecVar_SMOP1.mat', ...
    'Z:\Gilgamesh\kroppian\sNSGAIIRuns\island\sNSGAIIComparative_compDecVar_SMOP2.mat', ...
    'Z:\Gilgamesh\kroppian\sNSGAIIRuns\island\sNSGAIIComparative_compDecVar_SMOP3.mat', ...
    'Z:\Gilgamesh\kroppian\sNSGAIIRuns\island\sNSGAIIComparative_compDecVar_SMOP4.mat', ...
    'Z:\Gilgamesh\kroppian\sNSGAIIRuns\island\sNSGAIIComparative_compDecVar_SMOP5.mat', ...
    'Z:\Gilgamesh\kroppian\sNSGAIIRuns\island\sNSGAIIComparative_compDecVar_SMOP6.mat', ...
    'Z:\Gilgamesh\kroppian\sNSGAIIRuns\island\sNSGAIIComparative_compDecVar_SMOP7.mat', ...
    'Z:\Gilgamesh\kroppian\sNSGAIIRuns\island\sNSGAIIComparative_compDecVar_SMOP8.mat'  ...
    };


test_probs = { ...
    @SMOP1, ...
    @SMOP2, ...
    @SMOP3, ...
    @SMOP4, ...
    @SMOP5, ...
    @SMOP6, ...
    @SMOP7, ...
    @SMOP8  ...

    };


for f = 1:numel(output_files)
    config.prob = test_probs{f};
    load(output_files{f});
    plot_metric("HV",   "D", config, res_final);

end
